version: "3.8"
services:
    jenkins-docker: 
        image: docker:20.10.17-dind
          #image: docker:dind
        ports:
            - 3000:3000
            - 2376:2376
        volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        privileged: true
        networks:
            jenkins:
                aliases:
                    - docker
                    
    jenkins-blueocean:
        image: gchdeveloper/myjenkins-blueocean:1.1
        ports: 
            - 8080:8080
            # - 8443:8443
            - 50000:50000
        # command:
            # - "--httpPort=-1"
            # - "--httpsPort=8443"
            # - "--httpsKeyStore=/certs/client/jenkins.jks"
            # - "--httpsKeyStorePassword=your-strong-password"
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
            - ${HOME}:/home
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        networks:
            - jenkins
            
volumes:
    jenkins-docker-certs:
    jenkins-data:
    
networks:
    jenkins:
